steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_IMAGE}'
      - '--file'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - "-c"
      - |
          set -euo pipefail
          set_env_var() {
            local key="$1"
            local value="$2"
            CMD_ARGS+=("--set-env-vars=${key}=${value}")
          }

          set_env_with_default() {
            local key="$1"
            local raw="${2:-}"
            local fallback="$3"
            if [[ -z "${raw}" ]]; then
              raw="$fallback"
            fi
            set_env_var "$key" "$raw"
          }

          CMD_ARGS=(--image "${_IMAGE}" --region "${_REGION}" --platform managed --allow-unauthenticated)
          set_env_with_default "EMBEDDINGS_PROVIDER" "${_EMBEDDINGS_PROVIDER:-}" "openai"
          set_env_with_default "GOOGLE_AUTH_ENABLED" "${_GOOGLE_AUTH_ENABLED:-}" "false"
          set_env_with_default "GRAPH_ENABLED" "${_GRAPH_ENABLED:-}" "false"
          set_env_with_default "MAX_GRAPH_HOPS" "${_MAX_GRAPH_HOPS:-}" "2"
          set_env_with_default "LLM_RERANK_ENABLED" "${_LLM_RERANK_ENABLED:-}" "false"
          set_env_with_default "FACT_CHECK_STRICT" "${_FACT_CHECK_STRICT:-}" "false"
          set_env_with_default "FACT_CHECK_LLM_ENABLED" "${_FACT_CHECK_LLM_ENABLED:-}" "false"
          set_env_with_default "ADVANCED_MAX_SUBQUERIES" "${_ADVANCED_MAX_SUBQUERIES:-}" "3"
          set_env_with_default "ADVANCED_DEFAULT_K" "${_ADVANCED_DEFAULT_K:-}" "6"
          set_env_with_default "ADVANCED_DEFAULT_TEMPERATURE" "${_ADVANCED_DEFAULT_TEMPERATURE:-}" "0.2"
          if [[ -n "${_CORS_ALLOWED_ORIGINS:-}" ]]; then
            set_env_var "CORS_ALLOWED_ORIGINS" "${_CORS_ALLOWED_ORIGINS}"
          fi
          if [[ -n "${_SECRET_VARS:-}" ]]; then
            CMD_ARGS+=("--set-secrets=${_SECRET_VARS}")
          fi
          gcloud run deploy "${_SERVICE_NAME}" "${CMD_ARGS[@]}"

images:
  - '${_IMAGE}'

substitutions:
  _SERVICE_NAME: rag-playground-api
  _REGION: us-west1
  _EMBEDDINGS_PROVIDER: ""
  _GOOGLE_AUTH_ENABLED: ""
  _GRAPH_ENABLED: ""
  _MAX_GRAPH_HOPS: ""
  _LLM_RERANK_ENABLED: ""
  _FACT_CHECK_STRICT: ""
  _FACT_CHECK_LLM_ENABLED: ""
  _ADVANCED_MAX_SUBQUERIES: ""
  _ADVANCED_DEFAULT_K: ""
  _ADVANCED_DEFAULT_TEMPERATURE: ""
  _CORS_ALLOWED_ORIGINS: ""
  _SECRET_VARS: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'
