steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_IMAGE}'
      - '--file'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - "-c"
      - |
          set -euo pipefail
          set_env_var() {
            local key="$1"
            local value="$2"
            CMD_ARGS+=("--set-env-vars=${key}=${value}")
          }

          set_env_with_default() {
            local key="$1"
            local raw="${2:-}"
            local fallback="$3"
            if [[ -z "${raw}" ]]; then
              raw="$fallback"
            fi
            set_env_var "$key" "$raw"
          }

          CMD_ARGS=(--image "${_IMAGE}" --region "${_REGION}" --platform managed --allow-unauthenticated)
          set_env_with_default "EMBEDDINGS_PROVIDER" "${_EMBEDDINGS_PROVIDER:-}" "openai"
          set_env_with_default "FIRESTORE_CONFIG_ENABLED" "${_FIRESTORE_CONFIG_ENABLED:-}" "false"
          set_env_with_default "CONFIG_ENV" "${_CONFIG_ENV:-}" "prod"
          set_env_with_default "GOOGLE_AUTH_ENABLED" "${_GOOGLE_AUTH_ENABLED:-}" "true"
          # Pass through CORS from the trigger if set
          if [[ -n "${_CORS_ALLOWED_ORIGINS:-}" ]]; then
            set_env_var "CORS_ALLOWED_ORIGINS" "${_CORS_ALLOWED_ORIGINS}"
          fi
          if [[ -n "${_SECRET_VARS:-}" ]]; then
            CMD_ARGS+=("--set-secrets=${_SECRET_VARS}")
          fi
          # Log what we're deploying with
          if [[ -n "${_CORS_ALLOWED_ORIGINS:-}" ]]; then
            echo "Deploying ${_SERVICE_NAME} with CORS_ALLOWED_ORIGINS=${_CORS_ALLOWED_ORIGINS}"
          else
            echo "Deploying ${_SERVICE_NAME} with CORS_ALLOWED_ORIGINS=<unset>"
          fi
          echo "Deploying ${_SERVICE_NAME} with GOOGLE_AUTH_ENABLED=${_GOOGLE_AUTH_ENABLED:-true}"
          gcloud run deploy "${_SERVICE_NAME}" "${CMD_ARGS[@]}"

images:
  - '${_IMAGE}'

substitutions:
  _SERVICE_NAME: rag-playground-api
  _REGION: us-west1
  _EMBEDDINGS_PROVIDER: ""
  _FIRESTORE_CONFIG_ENABLED: ""
  _CONFIG_ENV: ""
  _GOOGLE_AUTH_ENABLED: ""
  _CORS_ALLOWED_ORIGINS: ""
  _SECRET_VARS: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'
