steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_IMAGE}'
      - '--file'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - "-c"
      - |
          set -euo pipefail
          CMD_ARGS=(--image "${_IMAGE}" --region "${_REGION}" --platform managed --allow-unauthenticated)
          if [[ -n "${_EMBEDDINGS_PROVIDER:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=EMBEDDINGS_PROVIDER=${_EMBEDDINGS_PROVIDER}")
          fi
          if [[ -n "${_GOOGLE_AUTH_ENABLED:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=GOOGLE_AUTH_ENABLED=${_GOOGLE_AUTH_ENABLED}")
          fi
          if [[ -n "${_GRAPH_ENABLED:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=GRAPH_ENABLED=${_GRAPH_ENABLED}")
          fi
          if [[ -n "${_MAX_GRAPH_HOPS:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=MAX_GRAPH_HOPS=${_MAX_GRAPH_HOPS}")
          fi
          if [[ -n "${_LLM_RERANK_ENABLED:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=LLM_RERANK_ENABLED=${_LLM_RERANK_ENABLED}")
          fi
          if [[ -n "${_FACT_CHECK_STRICT:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=FACT_CHECK_STRICT=${_FACT_CHECK_STRICT}")
          fi
          if [[ -n "${_FACT_CHECK_LLM_ENABLED:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=FACT_CHECK_LLM_ENABLED=${_FACT_CHECK_LLM_ENABLED}")
          fi
          if [[ -n "${_ADVANCED_MAX_SUBQUERIES:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=ADVANCED_MAX_SUBQUERIES=${_ADVANCED_MAX_SUBQUERIES}")
          fi
          if [[ -n "${_ADVANCED_DEFAULT_K:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=ADVANCED_DEFAULT_K=${_ADVANCED_DEFAULT_K}")
          fi
          if [[ -n "${_ADVANCED_DEFAULT_TEMPERATURE:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=ADVANCED_DEFAULT_TEMPERATURE=${_ADVANCED_DEFAULT_TEMPERATURE}")
          fi
          if [[ -n "${_CORS_ALLOWED_ORIGINS:-}" ]]; then
            CMD_ARGS+=("--set-env-vars=CORS_ALLOWED_ORIGINS=${_CORS_ALLOWED_ORIGINS}")
          fi
          if [[ -n "${_SECRET_VARS:-}" ]]; then
            CMD_ARGS+=("--set-secrets=${_SECRET_VARS}")
          fi
          gcloud run deploy "${_SERVICE_NAME}" "${CMD_ARGS[@]}"

images:
  - '${_IMAGE}'

substitutions:
  _SERVICE_NAME: rag-playground-api
  _REGION: us-west1
  _EMBEDDINGS_PROVIDER: ""
  _GOOGLE_AUTH_ENABLED: ""
  _GRAPH_ENABLED: ""
  _MAX_GRAPH_HOPS: ""
  _LLM_RERANK_ENABLED: ""
  _FACT_CHECK_STRICT: ""
  _FACT_CHECK_LLM_ENABLED: ""
  _ADVANCED_MAX_SUBQUERIES: ""
  _ADVANCED_DEFAULT_K: ""
  _ADVANCED_DEFAULT_TEMPERATURE: ""
  _CORS_ALLOWED_ORIGINS: ""
  _SECRET_VARS: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'
